name: Deploy Portfolio Site

on:
  push:
    branches: ["prod"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      # Install deps and build inside /site
      - name: Install dependencies
        working-directory: ./site
        run: npm install

      - name: Build site
        working-directory: ./site
        run: npm run build

      # Upload the dist/ output to S3
      - name: Upload to S3
        run: aws s3 sync ./site/dist s3://asad-ali-khan-static-portfolio-site --delete

      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id E2Z22J7ROYK8HK --paths "/*"
